---
- name: provision
  hosts: all
  remote_user: root
  roles:
    - nginx
    - role: ssl
      when: use_ssl
      domainsets:
        - domains:
          - "{{ webserver_name }}"
    - supervisor
    - nodejs
    - { role: postgresql, postgresql_server: yes, postgresql_client: yes, postgresql_backup_enabled: yes }
    - role: s3cmd
      when: postgresql_backup_to_s3
    - firewall
    - deploy_user
  post_tasks:
    - debug: msg="Successfully provisioned {{webserver_name}}"

